modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="cennymod"
version="1.0.0"
displayName="MrCennys Mod"
credits="Amongus, imposter?"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Even Hansen, Jared Kleinman"

[[dependencies.cennymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




